### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by yclchuxue** [devstream-io/website#35]
## Problem file
[01-index.md](https://github.com/devstream-io/website/blob/fix-quickstart-md/docs/01-index.md)
## Problem details
```
curl -o config.yaml https://raw.githubusercontent.com/devstream-io/devstream/main/examples/quickstart.yaml
```
This command does not seem to get the contents of file quikstart.yaml, but the contents of file Tools-quickstart.yaml.
```
curl -o tools-quickstart.yaml https://raw.githubusercontent.com/devstream-io/devstream/main/examples/tools-quickstart.yaml
```
This command failed,the file path error.

**Comment by daniel-hutao** [comment]
Thank you for your feedback, the documentation has been migrated back to the main repo https://github.com/devstream-io/devstream a while ago, so I had to close this issue first. Feel free to submit more issues to DevStream.
