### ISSUE TITLE
[Bug] Dark Mode does not work properly

### ISSUE THREAD

**Issue by iamppborah** [devstream-io/website#57]
### Without DarkMode👇
![BrightMode](https://user-images.githubusercontent.com/96339995/177009287-ee91728c-6642-4b7a-a294-ba065f486af9.jpg)

### With DarkMode👇
![DarkMode](https://user-images.githubusercontent.com/96339995/177009293-cc3fdda5-2955-464d-8493-2aee42f979e4.jpg)

### I am willing to submit a PR

**Comment by IronCore864** [comment]
Hi @ppborah, thanks for raising this issue! You are more than welcome to contribute a PR. Looking forward to it. Happy hacking!
