### ISSUE TITLE
Typos in the Documentation

### ISSUE THREAD

**Issue by ghost** [devstream-io/website#88]
Small fix is needed for the spelling of "developers" as discovered below.
<img width="1163" alt="Screenshot 2022-10-03 at 5 34 49 PM" src="https://user-images.githubusercontent.com/31725457/193572965-0459f2b3-2b78-42a9-8062-b37cded8ae96.png">

**Comment by daniel-hutao** [comment]
Hi, @JoshuaPoddoku. Thank you for raising this typos. I'll fix them in https://github.com/devstream-io/devstream/pull/1147.
